### ISSUE TITLE
Option On/Off for settings

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [LiYanan2004/SwiftUI-Haptics#1]
Hey,

In my app there will be a Settings - haptics, so user can disable haptics on my app. 
It would be cool if this package had such functionality.

**Comment by LiYanan2004** [comment]
@Volodymyr-13 Try this out.

```swift
import SwiftUI

extension View {
    @ViewBuilder
    func `if`(_ condition: @autoclosure @escaping () -> Bool, @ViewBuilder content: (_ content: Self) -> some View) -> some View {
        if condition() {
            content(self)
        } else {
            self
        ｝
    }
｝
```

**Comment by Anywhere-Music-Player** [comment]
I mean that option be like one for all, so you could easily enable/disable.

I don't know Swift at all, this is what chatGPT did with a code), but it works.
https://github.com/Volodymyr-13/SwiftUI-Haptics/commit/a419c7420383140f56ca6bcebffdd0d830177247

**Comment by LiYanan2004** [comment]
No. This package is a general one. In your revision, you use hard-coded `haptics` as your settings, but someone else may use `enableHaptics` as the name.

> @Volodymyr-13 Try this out.
> 
> ```swift
> import SwiftUI
> 
> extension View {
>     @ViewBuilder
>     func `if`(_ condition: @autoclosure @escaping () -> Bool, @ViewBuilder content: (_ content: Self) -> some View) -> some View {
>         if condition() {
>             content(self)
>         } else {
>             self
>         ｝
>     }
> ｝
> ```

Adding this modifier, you can simply write readable code.

```swift
YourView()
    .if(hapticEnabled) { view in
        view
            .hapticModifer() // Replace this with the modifier in my package.
    }
```

**Comment by Anywhere-Music-Player** [comment]
Yep, I did a hard-code, bcs this is for my app only, just showing it as example. 

I'm here talking about some general solution.. which is not require a code _.if(hapticEnabled_ in every place where I call haptics. 
Since in my code I'm just calling, since I just need a haptics on a button tap.
```
Button(action: {
    generator.hapticFeedbackOccurred(type: .soft)
}
```
So generator itself should check this, internally. To get more clean code and this is a switch inside a generator..

**Comment by LiYanan2004** [comment]
Oh, sorry for my misunderstanding of your issue. I'll add something to support that later.

**Comment by LiYanan2004** [comment]
Umm, maybe I'll not add this feature because as its name, namely generator, it should only focus on generate a haptic feedback. Any condition check should be executed externally.

You can still use your modified version or create a new class which inherit from `HapticGenerator` and override something inside it.
